name: build-test
on:
  push:
    branches: ["develop"]
  pull_request:
    types: [opened, synchronize]
 
jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
 
      - uses: pnpm/action-setup@v3
        with:
          version: 8
 
      - name: Generate Config File
          run: |
            echo "cognito:" > ./main/admin-panel/config.yml
            echo "  userPoolId: ${{ secrets.USER_POOL_ID }}" >> ./main/admin-panel/config.yml
            echo "  appClientId: ${{ secrets.APP_CLIENT_ID }}" >> ./main/admin-panel/config.yml
            echo "apiUrl: https://api.staging.scytix.com/" >> ./main/admin-panel/config.yml
            echo "secret_key: ${{ secrets.MY_SECRET }}" > ./main/admin-panel/config.yml
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
 
      - name: Install dependencies
        run: pnpm install
 
      - name: Build
        run: pnpm build
 
      - name: Test
        run: pnpm test