name: Dev

on:
  workflow_dispatch:
  push:
    branches:
      - feature/*
      - fix/*
      - spike/*

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build

  deploy-staging:
    name: Deploy Staging
    runs-on: ubuntu-22.04
    needs: build
    environment: Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
    
 
